export const supabasePassword = "aQE2Sr5oPSxwzmDI";
export const VITE_SUPABASE_URL = "https://tjqnstoqmvfjasxllifa.supabase.co";
export const VITE_SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqcW5zdG9xbXZmamFzeGxsaWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTYzNDA1MDYsImV4cCI6MjAzMTkxNjUwNn0.nnpvZIbPXHRMse0oVQAfLDxTzBQoeQFUTKiX4qHuTlo";
